#!/usr/bin/env bash
#
# tftarget-imports.sh — turn a tftarget manifest.tsv into Terraform `import {}`
# blocks, appended into each owning customer stack so it adopts the resource the
# dated tftarget root module created instead of recreating it.
#
# For every manifest row it appends an import block to <customer>/imports.tf
# (creating the file with a header on first write). It is IDEMPOTENT: a block
# whose `to = <address>` is already present in that file is skipped, so the
# script is safe to re-run as the manifest grows.
#
# Usage:
#   ./tftarget-imports.sh [manifest.tsv]   # defaults to newest .tftarget/*/manifest.tsv
#   IMPORT_FILE=imports.tf ./tftarget-imports.sh
#
# It also writes <manifest-dir>/import-commands.sh as a CLI alternative — note
# that `import {}` blocks targeting a count/for_each resource require Terraform
# >= 1.7; on older versions use the CLI form instead.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
export AWS_DEFAULT_PROFILE="${AWS_DEFAULT_PROFILE:-NRI_prod}"

IMPORT_FILE="${IMPORT_FILE:-imports.tf}"

# Locate the manifest: explicit arg, else the most recent dated one.
MANIFEST="${1:-$(ls -1dt "$SCRIPT_DIR"/.tftarget/*/manifest.tsv 2>/dev/null | head -1 || true)}"
if [ -z "$MANIFEST" ] || [ ! -f "$MANIFEST" ]; then
  echo "error: no manifest.tsv found (looked for $SCRIPT_DIR/.tftarget/*/manifest.tsv)" >&2
  exit 1
fi
MANIFEST_DIR="$(cd "$(dirname "$MANIFEST")" && pwd)"

# Append each import block into <customer>/imports.tf, skipping any that are
# already present. Process substitution (`< <(...)`) keeps the loop in the
# current shell so the counters survive.
appended=0
skipped=0
missing=0
touched=""
while IFS=$'\t' read -r customer plan_file source_address import_id target_resource; do
  dir="${plan_file%%/*}"                      # first path segment = customer root-module dir
  cdir="$SCRIPT_DIR/$dir"
  if [ ! -d "$cdir" ]; then
    echo "warn: customer dir not found, skipping: $dir" >&2
    missing=$((missing + 1))
    continue
  fi
  out="$cdir/$IMPORT_FILE"

  if [ ! -f "$out" ]; then
    cat > "$out" <<EOF
# Managed by tftarget-imports.sh — adopt tftarget-created resources into this stack.
# Blocks are idempotent (keyed by their 'to' address). Remove once imported.
EOF
  fi

  # Idempotency: skip if a block already targets this address (fixed-string
  # match so the [0]/dots in the address aren't treated as a regex).
  if grep -qF "to = $source_address" "$out"; then
    skipped=$((skipped + 1))
    continue
  fi

  cat >> "$out" <<EOF

import {
  to = $source_address
  id = "$import_id"
}
EOF
  appended=$((appended + 1))
  case " $touched " in *" $out "*) : ;; *) touched="$touched $out" ;; esac
done < <(tail -n +2 "$MANIFEST")

# Canonicalize only the files we appended to (best-effort).
for f in $touched; do
  terraform fmt "$f" >/dev/null 2>&1 || true
done

# CLI alternative: `terraform import` per resource, chdir'd into each stack.
# (Version-safe: works even where import {} blocks can't target count resources.)
CMDS="$MANIFEST_DIR/import-commands.sh"
{
  echo '#!/usr/bin/env bash'
  echo '# GENERATED by tftarget-imports.sh — CLI alternative to the import {} blocks.'
  echo 'set -euo pipefail'
  echo "export AWS_DEFAULT_PROFILE=\"\${AWS_DEFAULT_PROFILE:-NRI_prod}\""
  echo
  tail -n +2 "$MANIFEST" | while IFS=$'\t' read -r customer plan_file source_address import_id target_resource; do
    dir="${plan_file%%/*}"
    printf 'terraform -chdir=%q import %q %q\n' "$SCRIPT_DIR/$dir" "$source_address" "$import_id"
  done
} > "$CMDS"
chmod +x "$CMDS"

echo "Imports: $appended appended, $skipped already present$( [ "$missing" -gt 0 ] && echo ", $missing missing dirs" )."
echo "  written to: <customer>/$IMPORT_FILE"
echo "  cli form:   $CMDS"
